name: components
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.18.4 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/components/assets/images/whitearrowback.svg
    - packages/components/assets/images/whitearrowleft.svg
    - packages/components/assets/images/transactiontype.svg
    - packages/components/assets/images/coinimage.png
    - packages/components/assets/images/trendline.svg
    - packages/components/assets/images/detailedtransactionoptionscustom.svg
    - packages/components/assets/images/transactionarrow.svg
    - packages/components/assets/images/mask3.svg
    - packages/components/assets/images/mask2.svg
    - packages/components/assets/images/coinicon.svg
    - packages/components/assets/images/shape.png
    - packages/components/assets/images/arrowtoggle.svg
    - packages/components/assets/images/trendlinecustom.svg
    - packages/components/assets/images/coinicon.png
    - packages/components/assets/images/markettrendline.svg
    - packages/components/assets/images/maskcurrencyselector.png
    - packages/components/assets/images/checkmarksuffixicon.svg
    - packages/components/assets/images/masknextmonth.svg
    - packages/components/assets/images/maskpreviousmonth.svg
    - packages/components/assets/images/graphcustom.svg
    - packages/components/assets/images/optionscustom.png
    - packages/components/assets/images/profileicon.png
    - packages/components/assets/images/mask.png
    - packages/components/assets/images/arrowselectorvertical3.png
    - packages/components/assets/images/arrowselectorvertical2.png
    - packages/components/assets/images/arrowselectorvertical.png
    - packages/components/assets/images/combinedshape.png
    - packages/components/assets/images/showmoreicon.png
    - packages/components/assets/images/whitearrowright.svg
    - packages/components/assets/images/ellipse1.png
    - packages/components/assets/images/cointogglecustom.svg
    - packages/components/assets/images/increasecustom.svg
    - packages/components/assets/images/decreasecustom.svg
    - packages/components/assets/images/chartoptionscustom.svg
    - packages/components/assets/images/path4.svg
    - packages/components/assets/images/arrow.svg
    - packages/components/assets/images/passcodeframe.svg
    - packages/components/assets/images/ellipse17.png
    - packages/components/assets/images/ellipse18.png
    - packages/components/assets/images/ellipse19.png
    - packages/components/assets/images/ellipse20.png
    - packages/components/assets/images/ellipse21.png
    - packages/components/assets/images/ellipse22.png
    - packages/components/assets/images/group.svg
    - packages/components/assets/images/copyicon.svg
    - packages/components/assets/images/walletqrcodecustom.svg
    - packages/components/assets/images/completedstatuslogo.svg
    - packages/components/assets/images/pendingstatuslogo.svg
    - packages/components/assets/images/cancelledstatuslogo.svg
    - packages/components/assets/images/maskarrow2.svg
    - packages/components/assets/images/maskarrow1.svg
    - packages/components/assets/images/transactiontypearrow.svg
    - packages/components/assets/images/bxsdashboard.svg
    - packages/components/assets/images/walleticon.svg
    - packages/components/assets/images/ribookletfill.svg
    - packages/components/assets/images/group18.svg
    - packages/components/assets/images/chatbubbles.png
    - packages/components/assets/images/geniusappbarlogo.png
    - packages/components/assets/images/vector.svg
